/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jason
 */
public class Tela0 extends javax.swing.JFrame {

    /**
     * Creates new form Tela0
     */
    public Tela0() {
        initComponents();
        
        new Thread(){
        
        public void run() {
        
            for (int i=0; i<=100; i++){
                try {
                    sleep(40); 
                        labelProgress.setText(String.valueOf(i) + "%");
                        
                        if(i <= 10){                       
                            label.setText("Fazendo a conexao com o banco de dados");
                            sleep(30);                                                                          
                        }else if (i <= 30){
                            label.setText("Carregando o sistema");
                            sleep(30);  
                        } else if (i <= 70){
                            label.setText("Carregamento quase completo");  
                            sleep(30);
                        } else if (i <= 99){
                            label.setText("Carregamento completo");  
                            sleep(30);     
                        }else{
                            label.setText("Seu programa será iniciado.");                        
                            sleep(50);
                            dispose();
                            new view.Tela1().setVisible(true);
                        }
                         
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Tela0.class.getName()).log(Level.SEVERE, null, ex);
                    }       
            }        
        }
        
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelProgress = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();
        imgBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        labelProgress.setBackground(new java.awt.Color(34, 34, 34));
        labelProgress.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        labelProgress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelProgress);
        labelProgress.setBounds(620, 390, 50, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 40, 440, 110);

        label.setBackground(new java.awt.Color(34, 34, 34));
        label.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(label);
        label.setBounds(0, 390, 390, 40);

        loading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loader.gif"))); // NOI18N
        jPanel1.add(loading);
        loading.setBounds(580, 350, 130, 120);

        imgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bookBackground.jpg"))); // NOI18N
        imgBackground.setText("jLabel2");
        jPanel1.add(imgBackground);
        imgBackground.setBounds(0, 0, 750, 500);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 500);

        setSize(new java.awt.Dimension(760, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgBackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    javax.swing.JLabel label;
    private javax.swing.JLabel labelProgress;
    private javax.swing.JLabel loading;
    // End of variables declaration//GEN-END:variables
}
